services:
  - docker

branches:
  only:
    - master

os:
  - linux

env:
  global:
    - DATE=`TZ=America/New_York date "+%Y-%m-%d-%H%M"`
    - DOCKER_IMAGE="leanda/web-importer"


script:
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  # - docker build -t $DOCKER_TESTS_IMAGE:latest -f Sds.MetadataStorage.Tests/Dockerfile .
  # - yes | cp -rf Sds.MetadataStorage.Tests/.env.travis-ci Sds.MetadataStorage.Tests/.env
  # - cd Sds.MetadataStorage.Tests && docker-compose up --abort-on-container-exit

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE # Pushes both date and latest
